In [1]:
import numpy as np

In [2]:
arr=np.array([3,8,9,8])
print(arr)
print(type(arr))

[3 8 9 8]
<class 'numpy.ndarray'>


In [3]:
l=[]
for i in range(4):
    a=int(input("Enter No"))
    l.append(a)
print(np.array(l))

Enter No 3
Enter No 5
Enter No 5
Enter No 0


[3 5 5 0]


In [5]:
a=[[2,3,4,5],[4,4,3,4]]
print(np.array(a))
print(np.array(a).ndim)

[[2 3 4 5]
 [4 4 3 4]]
2


In [12]:
arr2=np.array([3,9,8,8])
print(arr*arr2)
print((arr*arr2).sum())
print(arr.sum())
print(arr*2)
print(np.dot(arr,arr2))

[ 9 72 72 64]
217
28
[ 6 16 18 16]
217


In [17]:
a3=[[3,8,9,8],
     [9,8,9,8],
     [12,89,34,76]]
arr3=np.array(a3)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(np.dot(arr3,arr2),np.dot(arr3,arr2).shape)
print(arr3.sum())
print(arr2.shape)


[[ 3  8  9  8]
 [ 9  8  9  8]
 [12 89 34 76]]
2
(3, 4)
[ 217  235 1717] (3,)
273
(4,)


In 1D array, shape is given as tuple such as (4,). In this first axis, here row will have 4 entities and there is no column in this.

In [18]:
print(arr3.dtype)

int32


In [19]:
a=np.matmul(arr3,arr2)
print(a)

[ 217  235 1717]


In [20]:
print(np.dot(arr3,arr2))

[ 217  235 1717]


In [22]:
b=np.transpose(arr2)
print(b)
print(arr2)
print(b.ndim,arr2.ndim)
print(b.shape,arr2.shape)

[3 9 8 8]
[3 9 8 8]
1 1
(4,) (4,)


In [23]:
arr3 @arr2 # Matrix multiplication can be done by either matpul,dot or @ sign

array([ 217,  235, 1717])

In [28]:
import os
print(os.getcwd())

C:\Users\visha\Machine Learning Tools


In [34]:
print(os.listdir(path=r'C:\Users\visha\Python Programming'))

['.git', '.ipynb_checkpoints', 'Binary Search.ipynb', 'Graph.ipynb', 'Heap.ipynb', 'LinkedList.ipynb', 'ML Basics.ipynb', 'Python basics.ipynb', 'Queque.ipynb', 'Recursion.ipynb', 'Sorting.ipynb', 'Stack.ipynb', 'Tree.ipynb']


In [38]:
os.mkdir(path=r'C:\Users\visha\Python Programming/test_folder')

In [42]:
import pandas as pd
t_data=pd.read_csv(r"C:\Users\visha\first_ML_Course\Dataset\Blue Book Bulldozers\Train.csv",delimiter=",")
print(t_data.head())


C:\Users\visha\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3185: DtypeWarning: Columns (13,39,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


   SalesID  SalePrice  MachineID  ModelID  datasource  auctioneerID  YearMade  \
0  1139246      66000     999089     3157         121           3.0      2004   
1  1139248      57000     117657       77         121           3.0      1996   
2  1139249      10000     434808     7009         121           3.0      2001   
3  1139251      38500    1026470      332         121           3.0      2001   
4  1139253      11000    1057373    17311         121           3.0      2007   

   MachineHoursCurrentMeter UsageBand         saledate  ...  \
0                      68.0       Low  11/16/2006 0:00  ...   
1                    4640.0       Low   3/26/2004 0:00  ...   
2                    2838.0      High   2/26/2004 0:00  ...   
3                    3486.0      High   5/19/2011 0:00  ...   
4                     722.0    Medium   7/23/2009 0:00  ...   

  Undercarriage_Pad_Width Stick_Length Thumb Pattern_Changer Grouser_Type  \
0                     NaN          NaN   NaN             

In [43]:
t_data_array=t_data.values
print(t_data_array)

[[1139246 66000 999089 ... nan 'Standard' 'Conventional']
 [1139248 57000 117657 ... nan 'Standard' 'Conventional']
 [1139249 10000 434808 ... nan nan nan]
 ...
 [6333338 11500 1887659 ... nan nan nan]
 [6333341 9000 1903570 ... nan nan nan]
 [6333342 7750 1926965 ... nan nan nan]]


In [48]:
print(t_data_array.ndim,t_data_array.shape,t_data_array.dtype,t_data_array.view(),t_data_array.any())

2 (401125, 53) object [[1139246 66000 999089 ... nan 'Standard' 'Conventional']
 [1139248 57000 117657 ... nan 'Standard' 'Conventional']
 [1139249 10000 434808 ... nan nan nan]
 ...
 [6333338 11500 1887659 ... nan nan nan]
 [6333341 9000 1903570 ... nan nan nan]
 [6333342 7750 1926965 ... nan nan nan]] 1139246


In [50]:
arr_1=np.array([[2,3,5,8],[7,1,2,3],[5,9,0,2]])
arr_2=np.array([[3,8,9,3],[9,0,3,6],[3,9,2,1]])

In [51]:
arr_1+arr_2

array([[ 5, 11, 14, 11],
       [16,  1,  5,  9],
       [ 8, 18,  2,  3]])

In [52]:
arr_1-arr_2

array([[-1, -5, -4,  5],
       [-2,  1, -1, -3],
       [ 2,  0, -2,  1]])

In [53]:
arr_1*arr_2

array([[ 6, 24, 45, 24],
       [63,  0,  6, 18],
       [15, 81,  0,  2]])

In [54]:
arr_1*3

array([[ 6,  9, 15, 24],
       [21,  3,  6,  9],
       [15, 27,  0,  6]])

In [56]:
b=arr_1==arr_2
print(b)

[[False False False False]
 [False False False False]
 [False  True False False]]


In [58]:
a=np.zeros([3,3,5])
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [60]:
b=np.ones([3,2])
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [64]:
c=np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [65]:
d=np.arange(10,90,3)
print(d)
d.shape

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88]


(27,)

In [67]:
d=np.arange(10,90,3).reshape([3,3,-1])
print(d)

[[[10 13 16]
  [19 22 25]
  [28 31 34]]

 [[37 40 43]
  [46 49 52]
  [55 58 61]]

 [[64 67 70]
  [73 76 79]
  [82 85 88]]]


In [68]:
print(d[1,2,1])

58


In [70]:
print(d[1:,2,:2])

[[55 58]
 [82 85]]


In [72]:
d=np.linspace(10,90,9)
print(d)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [73]:
e=np.random.rand(3,2)
print(e)

[[0.79145836 0.08803897]
 [0.63691374 0.61363108]
 [0.03195884 0.78732495]]


In [75]:
f=np.random.randn(4,5,5)
print(f)

[[[ 0.81603828 -0.23600651  1.94036188  0.48732349 -1.79294091]
  [-1.27909024  0.29686842  0.32562801 -1.19515677 -0.74849096]
  [-0.67512784 -0.83733654 -0.99793741  1.12079415 -0.48167722]
  [-0.26187488  0.64037106  0.69700409  0.44273844  1.48229836]
  [-0.13156022 -1.61284326  0.27202148 -0.31222082 -0.18777341]]

 [[-0.25570534  0.1477833   0.81718023 -1.29971176  0.94747386]
  [ 1.24812762 -2.07974693  0.37248319 -1.92921538 -1.06331386]
  [ 0.06101858 -0.9572175   1.01968765 -0.60041256  1.02326803]
  [ 0.93838565  0.64676055  0.40733126 -0.77639143  0.93824531]
  [ 0.19215746  1.17088541  0.71291942  0.50751099  0.73761819]]

 [[-0.34170079 -1.32682428 -0.05019963 -0.10324278  0.3463234 ]
  [-0.82156289 -0.99215716  0.29461234  0.08601984  0.9096587 ]
  [-1.63002102 -0.72711189  0.63432654  0.56590144 -1.37476343]
  [-0.36134614  0.88410225  0.45697316 -0.77151974  1.05405337]
  [-1.11777221  0.81277514 -0.48632837 -1.7053886   0.40953409]]

 [[-0.60850778  0.47822992 -0.2369