In [1]:
import numpy as np

In [9]:
import numpy as np

# Create a 3D NumPy array representing an image
x = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]]])

# Sum along the first axis (axis=0)
print(x.shape)
print(np.sum(x,axis=(2,1)))
z = np.sum(x, axis=1)
print("After summing along axis 2:\n", z)
print(z.shape)

# Sum along the remaining axis (axis=0) to get a single value
z = np.sum(z,axis=1)
print(z)
print(z.shape)

(2, 2, 3)
[21 57]
After summing along axis 2:
 [[ 5  7  9]
 [17 19 21]]
(2, 3)
[21 57]
(2,)


In [13]:
np.random.seed(1)
a= np.random.randn(2,4, 4, 3)
W = np.random.randn(4, 4, 3)
b = np.random.randn(1, 1, 1)

print(a)
print("+++++++++++++++++++++++++++++++++++++++++++++++++++")
print(b)
print("+++++++++++++++++++++++++++++++++++++++++++++++++++")
print(W)

[[[[ 1.62434536 -0.61175641 -0.52817175]
   [-1.07296862  0.86540763 -2.3015387 ]
   [ 1.74481176 -0.7612069   0.3190391 ]
   [-0.24937038  1.46210794 -2.06014071]]

  [[-0.3224172  -0.38405435  1.13376944]
   [-1.09989127 -0.17242821 -0.87785842]
   [ 0.04221375  0.58281521 -1.10061918]
   [ 1.14472371  0.90159072  0.50249434]]

  [[ 0.90085595 -0.68372786 -0.12289023]
   [-0.93576943 -0.26788808  0.53035547]
   [-0.69166075 -0.39675353 -0.6871727 ]
   [-0.84520564 -0.67124613 -0.0126646 ]]

  [[-1.11731035  0.2344157   1.65980218]
   [ 0.74204416 -0.19183555 -0.88762896]
   [-0.74715829  1.6924546   0.05080775]
   [-0.63699565  0.19091548  2.10025514]]]


 [[[ 0.12015895  0.61720311  0.30017032]
   [-0.35224985 -1.1425182  -0.34934272]
   [-0.20889423  0.58662319  0.83898341]
   [ 0.93110208  0.28558733  0.88514116]]

  [[-0.75439794  1.25286816  0.51292982]
   [-0.29809284  0.48851815 -0.07557171]
   [ 1.13162939  1.51981682  2.18557541]
   [-1.39649634 -1.44411381 -0.50446586]]

  

In [14]:
np.random.seed(1)
x = np.random.randn(4, 3, 3, 2)
print(x)

[[[[ 1.62434536 -0.61175641]
   [-0.52817175 -1.07296862]
   [ 0.86540763 -2.3015387 ]]

  [[ 1.74481176 -0.7612069 ]
   [ 0.3190391  -0.24937038]
   [ 1.46210794 -2.06014071]]

  [[-0.3224172  -0.38405435]
   [ 1.13376944 -1.09989127]
   [-0.17242821 -0.87785842]]]


 [[[ 0.04221375  0.58281521]
   [-1.10061918  1.14472371]
   [ 0.90159072  0.50249434]]

  [[ 0.90085595 -0.68372786]
   [-0.12289023 -0.93576943]
   [-0.26788808  0.53035547]]

  [[-0.69166075 -0.39675353]
   [-0.6871727  -0.84520564]
   [-0.67124613 -0.0126646 ]]]


 [[[-1.11731035  0.2344157 ]
   [ 1.65980218  0.74204416]
   [-0.19183555 -0.88762896]]

  [[-0.74715829  1.6924546 ]
   [ 0.05080775 -0.63699565]
   [ 0.19091548  2.10025514]]

  [[ 0.12015895  0.61720311]
   [ 0.30017032 -0.35224985]
   [-1.1425182  -0.34934272]]]


 [[[-0.20889423  0.58662319]
   [ 0.83898341  0.93110208]
   [ 0.28558733  0.88514116]]

  [[-0.75439794  1.25286816]
   [ 0.51292982 -0.29809284]
   [ 0.48851815 -0.07557171]]

  [[ 1.13162939

In [2]:
arr=np.array([3,8,9,8])
print(arr)
print(type(arr))

[3 8 9 8]
<class 'numpy.ndarray'>


In [15]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [6]:
l=[]
for i in range(4):
    a=int(input("Enter No"))
    l.append(a)
print(np.array(l))

Enter No 3
Enter No 4
Enter No 6
Enter No 7


[3 4 6 7]


In [7]:
a=[[2,3,4,5],[4,4,3,4]]
print(np.array(a))
print(np.array(a).ndim)

[[2 3 4 5]
 [4 4 3 4]]
2


In [11]:
arr2=np.array([3,9,8,8])
# print(arr*arr2)
# print((arr*arr2).sum())
print(arr.sum())
print(arr*2)
print(np.dot(arr,arr2))

28
[ 6 16 18 16]
217


In [14]:
a3=[[3,8,9,8],
     [9,8,9,8],
     [12,89,34,76]]
arr3=np.array(a3)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(np.dot(arr3,arr2),np.dot(arr3,arr3).shape)
print(arr3.sum())
print(arr2.shape)


[[ 3  8  9  8]
 [ 9  8  9  8]
 [12 89 34 76]]
2
(3, 4)


ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In 1D array, shape is given as tuple such as (4,). In this first axis, here row will have 4 entities and there is no column in this.

In [18]:
print(arr3.dtype)

int32


In [19]:
a=np.matmul(arr3,arr2)
print(a)

[ 217  235 1717]


In [20]:
print(np.dot(arr3,arr2))

[ 217  235 1717]


In [22]:
b=np.transpose(arr2)
print(b)
print(arr2)
print(b.ndim,arr2.ndim)
print(b.shape,arr2.shape)

[3 9 8 8]
[3 9 8 8]
1 1
(4,) (4,)


In [23]:
arr3 @arr2 # Matrix multiplication can be done by either matpul,dot or @ sign

array([ 217,  235, 1717])

In [28]:
import os
print(os.getcwd())

C:\Users\visha\Machine Learning Tools


In [78]:
print(os.listdir(path=r'C:\Users\visha'))
print(os.listdir("."))

['.bash_history', '.conda', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.Ld9VirtualBox', '.lesshst', '.matplotlib', '.ms-ad', '.popsql.json', '.spyder-py3', '.viminfo', 'anaconda3', 'AppData', 'Application Data', 'Computational_Linear_algebra', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'first_ML_Course', 'IntelGraphicsProfiles', 'Local Settings', 'Machine Learning Tools', 'MS Office Crack Version', 'Music', 'My Documents', 'NetHood', 'ntuser.dat', 'ntuser.dat.log1', 'ntuser.dat.log2', 'ntuser.dat{0f8ca85f-03df-11ec-97bb-34f64bffadd3}.TM.blf', 'ntuser.dat{0f8ca85f-03df-11ec-97bb-34f64bffadd3}.TMContainer00000000000000000001.regtrans-ms', 'ntuser.dat{0f8ca85f-03df-11ec-97bb-34f64bffadd3}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer000000

In [38]:
os.mkdir(path=r'C:\Users\visha\Python Programming/test_folder')

In [42]:
import pandas as pd
t_data=pd.read_csv(r"C:\Users\visha\first_ML_Course\Dataset\Blue Book Bulldozers\Train.csv",delimiter=",")
print(t_data.head())


C:\Users\visha\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3185: DtypeWarning: Columns (13,39,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


   SalesID  SalePrice  MachineID  ModelID  datasource  auctioneerID  YearMade  \
0  1139246      66000     999089     3157         121           3.0      2004   
1  1139248      57000     117657       77         121           3.0      1996   
2  1139249      10000     434808     7009         121           3.0      2001   
3  1139251      38500    1026470      332         121           3.0      2001   
4  1139253      11000    1057373    17311         121           3.0      2007   

   MachineHoursCurrentMeter UsageBand         saledate  ...  \
0                      68.0       Low  11/16/2006 0:00  ...   
1                    4640.0       Low   3/26/2004 0:00  ...   
2                    2838.0      High   2/26/2004 0:00  ...   
3                    3486.0      High   5/19/2011 0:00  ...   
4                     722.0    Medium   7/23/2009 0:00  ...   

  Undercarriage_Pad_Width Stick_Length Thumb Pattern_Changer Grouser_Type  \
0                     NaN          NaN   NaN             

In [43]:
t_data_array=t_data.values
print(t_data_array)

[[1139246 66000 999089 ... nan 'Standard' 'Conventional']
 [1139248 57000 117657 ... nan 'Standard' 'Conventional']
 [1139249 10000 434808 ... nan nan nan]
 ...
 [6333338 11500 1887659 ... nan nan nan]
 [6333341 9000 1903570 ... nan nan nan]
 [6333342 7750 1926965 ... nan nan nan]]


In [48]:
print(t_data_array.ndim,t_data_array.shape,t_data_array.dtype,t_data_array.view(),t_data_array.any())

2 (401125, 53) object [[1139246 66000 999089 ... nan 'Standard' 'Conventional']
 [1139248 57000 117657 ... nan 'Standard' 'Conventional']
 [1139249 10000 434808 ... nan nan nan]
 ...
 [6333338 11500 1887659 ... nan nan nan]
 [6333341 9000 1903570 ... nan nan nan]
 [6333342 7750 1926965 ... nan nan nan]] 1139246


In [3]:
arr_1=np.array([[2,3,5,8],[7,1,2,3],[5,9,0,2]])
arr_2=np.array([[3,8,9,3],[9,0,3,6],[3,9,2,1]])

In [51]:
arr_1+arr_2

array([[ 5, 11, 14, 11],
       [16,  1,  5,  9],
       [ 8, 18,  2,  3]])

In [4]:
print(arr_1+5)

[[ 7  8 10 13]
 [12  6  7  8]
 [10 14  5  7]]


In [52]:
arr_1-arr_2

array([[-1, -5, -4,  5],
       [-2,  1, -1, -3],
       [ 2,  0, -2,  1]])

In [53]:
arr_1*arr_2

array([[ 6, 24, 45, 24],
       [63,  0,  6, 18],
       [15, 81,  0,  2]])

In [54]:
arr_1*3

array([[ 6,  9, 15, 24],
       [21,  3,  6,  9],
       [15, 27,  0,  6]])

In [56]:
b=arr_1==arr_2
print(b)

[[False False False False]
 [False False False False]
 [False  True False False]]


In [58]:
a=np.zeros([3,3,5])
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [60]:
b=np.ones([3,2])
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [64]:
c=np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [65]:
d=np.arange(10,90,3)
print(d)
d.shape

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88]


(27,)

In [67]:
d=np.arange(10,90,3).reshape([3,3,-1])
print(d)

[[[10 13 16]
  [19 22 25]
  [28 31 34]]

 [[37 40 43]
  [46 49 52]
  [55 58 61]]

 [[64 67 70]
  [73 76 79]
  [82 85 88]]]


In [68]:
print(d[1,2,1])

58


In [70]:
print(d[1:,2,:2])

[[55 58]
 [82 85]]


In [72]:
d=np.linspace(10,90,9)
print(d)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [73]:
e=np.random.rand(3,2)
print(e)

[[0.79145836 0.08803897]
 [0.63691374 0.61363108]
 [0.03195884 0.78732495]]


In [75]:
f=np.random.randn(4,5,5)
print(f)

[[[ 0.81603828 -0.23600651  1.94036188  0.48732349 -1.79294091]
  [-1.27909024  0.29686842  0.32562801 -1.19515677 -0.74849096]
  [-0.67512784 -0.83733654 -0.99793741  1.12079415 -0.48167722]
  [-0.26187488  0.64037106  0.69700409  0.44273844  1.48229836]
  [-0.13156022 -1.61284326  0.27202148 -0.31222082 -0.18777341]]

 [[-0.25570534  0.1477833   0.81718023 -1.29971176  0.94747386]
  [ 1.24812762 -2.07974693  0.37248319 -1.92921538 -1.06331386]
  [ 0.06101858 -0.9572175   1.01968765 -0.60041256  1.02326803]
  [ 0.93838565  0.64676055  0.40733126 -0.77639143  0.93824531]
  [ 0.19215746  1.17088541  0.71291942  0.50751099  0.73761819]]

 [[-0.34170079 -1.32682428 -0.05019963 -0.10324278  0.3463234 ]
  [-0.82156289 -0.99215716  0.29461234  0.08601984  0.9096587 ]
  [-1.63002102 -0.72711189  0.63432654  0.56590144 -1.37476343]
  [-0.36134614  0.88410225  0.45697316 -0.77151974  1.05405337]
  [-1.11777221  0.81277514 -0.48632837 -1.7053886   0.40953409]]

 [[-0.60850778  0.47822992 -0.2369

In [100]:
c=open(r'C:\Users\visha\Downloads\FINAL450 (1).xlsx',"r")
print(c.read())

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 16: character maps to <undefined>

In [102]:
c=open(r'C:\Users\visha\Downloads\Shweta_resume.docx',"rb")
print(c.read())

b'PK\x03\x04\x14\x00\x02\x00\x08\x00\xd6@cVI.WY\x93\x14\x00\x00\xd3\xc6\x00\x00\x11\x00\x11\x00word/document.xmlUT\r\x00\x07\xa3\xaa\x01d\xa3\xaa\x01d\xa3\xaa\x01d\xed=k\x8f\xe38r\xdf\xf3+\x0c\x1f\x10$@w[\xef\x87w{\x16~t\xefL2\xb37\x99\xed\xbd A\x80\x03-\xd36odQ\'\xc9\xee\xee\xf9t?#\xf9{\xf7KB\xeaa\xcb\x92,QR\xb9gf\xaf\xc7\xc0\xb4\x1fb\xb1X,V\x15\x8bU\xc5\x1f\x7fz\xda\xba\x83=\x0eBB\xbd\xdb\xa1|#\r\x07\xd8s\xe8\x92x\xeb\xdb\xe1o\x0f\xf7\xd7\xd6p\x10F\xc8["\x97z\xf8v\xf8\x8c\xc3\xe1Oo\xfe\xe9\xc7\xc7\xf1\x92:\xbb-\xf6\xa2\x01\x83\xe0\x85\xe3=\xfbq\x13E\xfex4\n\x9d\r\xde\xa2\xf0\x86\xfa\xd8c?\xaeh\xb0E\x11\xfb\x18\xacG[\x14|\xde\xf9\xd7\x0e\xdd\xfa("\x0b\xe2\x92\xe8y\xa4H\x921L\xc1\xd0\xdb\xe1.\xf0\xc6)\x88\xeb-q\x02\x1a\xd2U\xc4\x9b\x8c\xe9jE\x1c\x9c\xfe\xc9Z\x04"\xfd&M\xe6)\xcaq\x8f\xa3\x00\xbb\x0c\x07\xea\x85\x1b\xe2\x87\x19\xb4mWh\xec\xc7M\x06d_7\x88\xfd\xd6\xcd\x9e{\xf4Ez[\x06\xe8\x91M\xc7\xd6M:z\xa4\xc1\xd2\x0f\xa8\x83\xc3\x90};O~<@\x94%\x01\x02r\x10\x87\x16"(\x9c\xf6\x99a\xb2E\xc4

In [18]:
a=np.array([1,2,3,4,6])
print(sum(np.exp(a)))

488.2198183764567


In [2]:
# Generate a random number 

In [4]:
from numpy import random

x=random.randint(1,7)
print(x)

3


In [5]:
x=random.rand()  # output wil be between 0 to 1
print(x)

0.43006293389458494


In [6]:
x=random.randint(5,100,size=(3,4,5))
print(x)

[[[99 68 17 63  8]
  [40 24 85 29 68]
  [70 92 17 66 63]
  [17 87 92 60 39]]

 [[49 33 62 83 19]
  [95  9  9 17 88]
  [39 14 70 15 90]
  [49 66 77 47 29]]

 [[33 22 39 95 93]
  [20 37 93 87 48]
  [55 18 76 23 60]
  [95 39 30 73 98]]]


In [10]:
x=random.randn(5,7)
print(x)

[[ 0.72759831 -2.24826335 -0.59386094  0.07289908 -1.48937928  0.47957082
  -0.48195511]
 [ 0.19801388  0.49668927 -0.8988893  -1.50912516 -2.0610984   0.11220617
   0.45832756]
 [-0.24461547 -0.50047652  0.38409087 -0.46584286 -0.24451749 -0.57835784
  -0.01429671]
 [ 0.91629496 -0.80167406 -0.4598751   0.02364974  0.6369539   0.03112085
  -2.32958123]
 [-0.54395848 -1.65947049  1.85712346  0.9056085   0.30073602  2.43297302
  -0.50822   ]]


In [12]:
x=random.choice(("H","T"),size=(4,5))
print(x)

[['T' 'H' 'T' 'H' 'T']
 ['T' 'T' 'T' 'H' 'H']
 ['T' 'T' 'T' 'T' 'H']
 ['T' 'T' 'H' 'H' 'T']]


In [13]:
print(np.full((3,5),7.5))

[[7.5 7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5 7.5]]
