In [2]:
import tensorflow as tf

In [17]:
# Intiatization of tensor

x=tf.constant([4],shape=(2,3), dtype=tf.int32)
x=tf.constant([[1,2,3],[3,4,5]])

x=tf.ones((3,2))
x=tf.zeros((2,3))
x=tf.eye(2)
x=tf.random.normal((3,3))
x=tf.random.uniform((3,3))
x=tf.range(start=10, limit=100, delta=10)
x=tf.cast(x,dtype=tf.float32)

print(x)

tf.Tensor([10. 20. 30. 40. 50. 60. 70. 80. 90.], shape=(9,), dtype=float32)


In [59]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

z=tf.add(x,y)
z=x+y

z-tf.subtract(x,y)
z=x-y

z=tf.divide(x,y)
z=x/y

z=tf.multiply(x,y)
z=x*y

z=tf.tensordot(x,y,axes=0)
z=tf.reduce_sum(x*y,axis=0)

x=tf.ones((2,3))*2
y=tf.ones((3,2))*3

z=tf.matmul(x,y)
print(z)

z=tf.tensordot(x,y,axes=0)
# print(x,y)
# print(z)

# INdexing
x=tf.constant([0,1,2,3,4,5,6,7])
indices=tf.gather(x,x[:4])
print(indices)

x=tf.constant([[2,3],
              [4,5],
              [6,8]])

print(x[0:3:2,0])

## reshaping

x=tf.range(9)
x=tf.reshape(x,(3,3))
print(x)

x=tf.transpose(x)
print(x)

tf.Tensor(
[[18. 18.]
 [18. 18.]], shape=(2, 2), dtype=float32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([2 6], shape=(2,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [1]:
import tensorflow as tf

tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Maximum value along each column (axis=0)
max_values_along_columns = tf.math.reduce_max(tensor, axis=0)
print(max_values_along_columns)  # Output: [4 5 6]

# Maximum value along each row (axis=1)
max_values_along_rows = tf.math.reduce_max(tensor, axis=1)
print(max_values_along_rows)  # Output: [3 6]


tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


In [2]:
p=tf.constant([2,3,4,5,6])
print(p>5)

tf.Tensor([False False False False  True], shape=(5,), dtype=bool)


In [4]:
p=tf.random.normal(shape=(2,3,4))
print(p)
print(p>5)

tf.Tensor(
[[[-0.04140493  0.4115787   0.4322567  -0.2753911 ]
  [ 0.8647774   0.5185812  -0.15937434  0.831804  ]
  [-2.5820794   0.2711955  -0.5291506  -0.07123774]]

 [[-0.34853476 -1.2821816   1.0556811   0.28297794]
  [ 0.36705038 -0.51085883  1.158644   -0.2451036 ]
  [-0.98983663  0.25683382 -0.82478267 -0.55983067]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]], shape=(2, 3, 4), dtype=bool)


In [7]:
a=tf.random.normal(shape=(3,4,5))
print(a)

b=tf.reshape(a,shape=[5,-1])
c=tf.transpose(tf.reshape(-1,5))
print(b==c)

tf.Tensor(
[[[ 0.8762568  -0.578346   -0.3336025   0.16450328  0.24662782]
  [-0.32351804  0.6116744  -0.82204205  0.5106907   0.7385134 ]
  [-0.6165734  -0.0360646   0.4260435   1.5378385  -0.04289336]
  [ 1.4695467   0.13394377 -0.3366936  -1.1957442   0.9428554 ]]

 [[-0.60635877  0.63954353  0.01600436 -0.10319051 -1.9700714 ]
  [ 1.1308284   2.3599513  -0.80270904  2.008391    1.6955391 ]
  [-1.6994324   0.26288822  2.2430334  -0.03062435  0.5489859 ]
  [ 2.1792257   1.1641186   0.22845104  1.5331235  -0.61935514]]

 [[ 1.8448001   1.7618515  -0.78562874 -0.6734656  -1.1837806 ]
  [ 2.922366   -0.04045252  0.42720655  0.9941797  -1.4557817 ]
  [ 0.13343038 -1.284039   -0.5601984  -0.32424423  3.2818105 ]
  [ 1.0731927  -0.5552292   0.8340205   1.5963858   3.238045  ]]], shape=(3, 4, 5), dtype=float32)


InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 1 values, but the requested shape has 5 [Op:Reshape] name: 